# Generated by Django 5.0.6 on 2024-05-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='no-name>', max_length=100)),
                ('lastname', models.CharField(default='<no-name>', max_length=100)),
                ('password', models.CharField(default='<no-passwd>', max_length=255)),
                ('email', models.EmailField(default='<no-email>', max_length=254)),
                ('rollno', models.IntegerField(default=0)),
            ],
        ),
    ]
