# Generated by Django 5.0.6 on 2024-05-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_student_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.JSONField(default={'no-courses': 1}),
        ),
    ]
