# Generated by Django 5.0.6 on 2024-05-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.IntegerField(default=0),
        ),
    ]
